// <auto-generated />
namespace Merp.Registry.QueryStack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Person));
        
        string IMigrationMetadata.Id
        {
            get { return "201407181101345_Person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
