// <auto-generated />
namespace Merp.Registry.QueryStack.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Registry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Registry));
        
        string IMigrationMetadata.Id
        {
            get { return "201407211518194_Registry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
