// <auto-generated />
namespace Merp.Web.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class IncomingInvoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncomingInvoice));
        
        string IMigrationMetadata.Id
        {
            get { return "201407311251549_IncomingInvoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
